In [1]:
#!/usr/bin/env python
# coding: utf-8

# In[15]:


#OMDb API practice

#omdb website
basic_url = 'http://www.omdbapi.com/?'

#parameters to search certain info

#Parameter	Required	Valid options	Default Value	Description
#   s   	Yes 	                    	<empty> 	Movie title to search for.
#  type 	 No 	movie, series, episode 	<empty> 	Type of result to return.
#   y   	No  	                    	<empty> 	Year of release.
#   r   	No      	json, xml       	json    	The data type to return.
#page New!	No          	1-100       	1       	Page number to return.
#callback	No  	                    	<empty> 	JSONP callback name.
#   v   	No  	                    	1       	API version (reserved for future use)
parameters = 'i=tt3896198&' #this is a IMDb ID for the movie "Guardians of the Galaxy Vol. 2" 
                            #'i' is the parameter to search film by ID

key = 'apikey=ee06fce6'

#building url notes:
# - url must have 'paramters' before 'key' - this creates the issue of mapping what the user inputs into a 'parameter'
# - each 'parameter' of url after basic_url must be followed by '&' 
# - each 'parameter' follows this patern -- '[Parameter]=[valid option]'
# - [valid options] that contain spaces are separated by '+'
# - example - 'http://www.omdbapi.com/?t=Blade+Runner&y=1982' -- '&' + key must be provided after for link to work
#                                      t-title        y-year


url = basic_url + parameters + key
print(url)


# In[37]:


#pandas practice with OMDb api

import pandas as pd
import requests
import json

response = requests.get(url)
movie = response.json()
movie_df = pd.DataFrame(movie) #why does this return the same thing 3 times? 
                               #Do multiple search results come up in IMDb?
movie_df


# In[47]:


#Webbrowser practice

import webbrowser # I used this in:
                  # 2019-Spring-Learn-Python-jfeith-su/content/lessons/07/Class-Coding-Lab/CCL-Strings.ipynb
                  # for reference. There is a urlChecker function we may want to use from that lab



webbrowser.open_new_tab('https://www.youtube.com/results?search_query=guardians+of+the+galaxy+vol+2+trailer')

# I'm thinking it will be easy to bring people to the YouTube search results with this basic url:
# 'https://www.youtube.com/results?search_query='
# and then, looking at the format of the url above, we can replace spaces with '+'s to get them to the search results
# note: figuring out how to get them to the actual video does not have as simple of a url format, so I think we should
#       bring them to the search results page instead
# I don't know how to open the link without going right to the tab, like command-clicking a url, so maybe we'll ask
# the user if they want to go to the trailer

# p.s. - our mentor suggested finding a way to put the poster in the program, but the poster api doesn't work unless you donate money


# In[ ]:





# In[ ]:

http://www.omdbapi.com/?i=tt3896198&apikey=ee06fce6

True

In [4]:
movie_df.head(1)

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Guardians of the Galaxy Vol. 2,2017,PG-13,05 May 2017,136 min,"Action, Adventure, Comedy, Sci-Fi",James Gunn,"James Gunn, Dan Abnett (based on the Marvel co...","Chris Pratt, Zoe Saldana, Dave Bautista, Vin D...",The Guardians struggle to keep together as a t...,...,67,7.7,"458,168",tt3896198,movie,22 Aug 2017,"$389,804,217",Walt Disney Pictures,https://marvel.com/guardians,True

In [16]:
url = 'http://www.omdbapi.com/?t=Star+Wars&' + key

response = requests.get(url)
movie = response.json()
movie_df = pd.DataFrame(movie)

movie_df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,Response
0,Star Wars: Episode IV - A New Hope,1977,PG,25 May 1977,121 min,"Action, Adventure, Fantasy, Sci-Fi",George Lucas,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher, Pet...",Luke Skywalker joins forces with a Jedi Knight...,...,90,8.6,"1,109,357",tt0076759,movie,21 Sep 2004,N/A,20th Century Fox,http://www.starwars.com/episode-iv/,True
1,Star Wars: Episode IV - A New Hope,1977,PG,25 May 1977,121 min,"Action, Adventure, Fantasy, Sci-Fi",George Lucas,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher, Pet...",Luke Skywalker joins forces with a Jedi Knight...,...,90,8.6,"1,109,357",tt0076759,movie,21 Sep 2004,N/A,20th Century Fox,http://www.starwars.com/episode-iv/,True
2,Star Wars: Episode IV - A New Hope,1977,PG,25 May 1977,121 min,"Action, Adventure, Fantasy, Sci-Fi",George Lucas,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher, Pet...",Luke Skywalker joins forces with a Jedi Knight...,...,90,8.6,"1,109,357",tt0076759,movie,21 Sep 2004,N/A,20th Century Fox,http://www.starwars.com/episode-iv/,True